### ISSUE TITLE
Remove windows hack for running scripts in build actions

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#454]
Revert #448 once dune is able to hide window's inability to run scripts.

**Comment by gpetiot** [comment]
Fixed by #664 ?

**Comment by jberdine** [comment]
It's not really fixed. There is still the `%%{dep` stuff needed in the `dune` file since we're not allowed to make `gen_version.ml` a shebang script either.

**Comment by Julow** [comment]
@jberdine The `%{dep:...}` syntax is to tell dune what are the dependencies. The real "hack" is calling the interpreter explicitly: `ocaml %{dep:...}`.
I don't think that is an uncommon way to call a script. What do you think?
