### ISSUE TITLE
Several small bugs with first class modules

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#47]
Hello,
I found a couple errors when running ocamlformat v0.2 on our code base.

- In an interface file (same as #29 which was fixed for implementations):

```ocaml
module type S = sig end
type t = (module S)
```

- Patterns are rewritten without parens:

```ocaml
module type S = sig val x : int end

module M = struct
  let x = 0
end

let m = (module M : S)

let () =
  let (module M : S) = m in (* error here *)
  ()
```

The pattern line gets rewritten as `let module M : module S = m in` which is invalid syntax.

I think that it's the same issue but:

```ocaml
module type S = sig val x : int end

module M = struct
  let x = 0
end

let m = (module M : S)

let f ((module M : S) as u) = (* error here *)
  ignore u;
  M.x
```

The error line gets rewritten as `let f (module M: S as u) = ignore u ; M.x`

- module constraints are not rewritten correctly

```ocaml
module type S = sig
  type a
  val va : a
  type b
  val vb : b
end

let f (module M : S with type a = int and type b = int) = M.va + M.vb
```

The last line gets rewritten as `let f (module M: S with type a = int and b = int) = M.va + M.vb`. (note the missing `type`).

Thanks a lot!

**Comment by jberdine** [comment]
Thanks! These should be fixed now.

**Comment by leviroth** [comment]
I found that the let-binding issue still occurs if the signature is not given explicitly on the left-hand side:

```ocaml
module type S = sig val x : int end

module M = struct
  let x = 0
end

let m = (module M : S)

let () =
  let (module M) = m in
  (*           ^--- difference *)
  ()
```

**Comment by jberdine** [comment]
Thanks! Should be fixed now.

**Comment by emillon** [comment]
Not sure whether to reopen this or a new one, but the following:

    let f ((module M : S) as x) = ()

gets rewritten to:

    let f (module M : S as x) = ()

which is a syntax error.

Thanks!

**Comment by jberdine** [comment]
Clearly there hasn't been enough testing of first-class modules. Is the/similar code you are trying to format available publicly?

**Comment by emillon** [comment]
The code base these examples have been extracted from an internal project, which is not public. The only things `ocamlformat` fails on now are related to objects.

For first-class modules, you can have a look at https://github.com/cryptosense/pkcs11 which uses similar patterns with first-class modules, but now it passes with `ocamlformat` `master` without any errors. I'd recommend setting up a proper test suite rather than (or maybe in addition to) relying on external projects.

Thanks!

**Comment by jberdine** [comment]
Yes, the missing test suite is a definite weakness currently. I have been hoping to come up with something systematic, to cover all the parsetree combinations in some known way, but have not had the time so far. But looking at real code is still useful from the perspective of seeing how ugly the generated output is for various styles of code.
